// <auto-generated />
using System;
using CashRegister.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CashRegister.Migrations
{
    [DbContext(typeof(CashRegisterDataContext))]
    partial class CashRegisterDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CashRegister.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bananen 1kg",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Äpfel 1kg",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trauben Weiß 500g",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Himbeeren 125g",
                            Price = 1.89m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Karotten 500g",
                            Price = 1.19m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eissalat 1 Stück",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zucchini 1 Stück",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Knoblauch 150g",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Joghurt 200g",
                            Price = 0.49m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Butter",
                            Price = 2.59m
                        });
                });

            modelBuilder.Entity("CashRegister.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptId");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("CashRegister.Models.ReceiptLine", b =>
                {
                    b.Property<int>("ReceiptLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptLine");
                });

            modelBuilder.Entity("CashRegister.Models.ReceiptLine", b =>
                {
                    b.HasOne("CashRegister.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("CashRegister.Models.Receipt", null)
                        .WithMany("ReceiptLines")
                        .HasForeignKey("ReceiptId");
                });
#pragma warning restore 612, 618
        }
    }
}
